config/routes.rb
Rails.application.routes.draw do
  root to: 'clients#index'
  resources :clients, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  private
  def strong_params
    params.require(:client).permit(:name, :address, :photo)
  end

  def find_client
    @client = Client.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/index.html.erb
<!-- banner -->
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.35) 0%, rgba(0,36,61,0.35) 50%), url('<%= image_path "https://unsplash.it/1700/400?image=1078" %>')">
  <div class="banner-content">
    <h2>Meet our clients</h2>
  </div>
</div>
<!-- end of banner -->
<div class="container">
  <div class="client-list">
    <div class="row tect-center">
    <% @clients.each do |client| %>
      <div class="col-xs-12 col-sm-4 col-md-2 col-md-offset-1 col-md-offset-1 text-center client-card">
        <%= link_to image_tag(client.photo), client_path(client) %>
        <p><%= link_to client.name, client_path(client)%></p>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="container">
  <div class="user-information">
    <div class="row">
      <div class="col-sm-12 col-md-4 col-md-offset-1 client-img">
        <%= image_tag @client.photo %>
      </div>
      <div class="col-sm-12 col-md-6 ">
        <h2><%= @client.name %></h2>
        <h3><%= @client.address %></h3>
        <%= link_to "back", clients_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Our Clients</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>